steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'build'
      - '-t'
      - 'us-central1-docker.pkg.dev/crystaltides-prod/crystaltides-repo/frontend'
      - '-f'
      - 'apps/web-client/Dockerfile'
      - '--build-arg'
      - 'VITE_SUPABASE_URL=https://gyoqnqvqhuxlcbrvtfia.supabase.co'
      - '--build-arg'
      - 'VITE_SUPABASE_ANON_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd5b3FucXZxaHV4bGNicnZ0ZmlhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjUyOTk0MTEsImV4cCI6MjA4MDg3NTQxMX0.eLU_-IrRfixx7dpR9jeiEoOT1u-exQMhIsxSXVINbRA'
      - '--build-arg'
      - 'VITE_API_URL=https://api.crystaltidessmp.net/api' 
      - '.'
images:
  - 'us-central1-docker.pkg.dev/crystaltides-prod/crystaltides-repo/frontend'
