-- Create table for Interactive Rules
CREATE TABLE IF NOT EXISTS public.server_rules (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category VARCHAR(255) NOT NULL, -- Examples: 'Comportamiento', 'Chat', 'PvP', 'Clientes', 'Staff'
    title VARCHAR(255) NOT NULL,
    content TEXT NOT NULL,          -- Markdown content description
    color VARCHAR(7) DEFAULT '#6366f1', -- HEX Color
    sort_order INTEGER DEFAULT 0,   -- Lower number = Higher priority
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable RLS
ALTER TABLE server_rules ENABLE ROW LEVEL SECURITY;

-- Policies
CREATE POLICY "Public Read Access" ON server_rules
    FOR SELECT USING (true);

CREATE POLICY "Admin All Access" ON server_rules
    FOR ALL TO authenticated
    USING (
        EXISTS (
            SELECT 1 FROM public.profiles 
            WHERE id = auth.uid() 
            AND role IN ('admin', 'neroferno', 'killu', 'killuwu', 'developer')
        )
    );

-- Insert some example initial data
-- INSERT INTO public.server_rules (category, title, content, sort_order) VALUES
-- ('Comportamiento', 'Respeto Mutuo', 'Todos los jugadores deben tratarse con respeto. Insultos graves, racismo o discriminación resultarán en sanción inmediata.', 1),
-- ('Chat', 'No Spam', 'Evita enviar mensajes repetitivos o molestos en el chat global.', 1);
