-- SECURITY HARDENING
-- Tables: system_logs, profiles

-- 1. SYSTEM LOGS
-- Backend-only access. No public policies needed as Service Role bypasses RLS.
CREATE TABLE IF NOT EXISTS public.system_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) ON DELETE SET NULL,
    username TEXT,
    action TEXT NOT NULL,
    details TEXT,
    source TEXT DEFAULT 'web',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.system_logs ENABLE ROW LEVEL SECURITY;

-- Remove any existing policies to be safe (Deny All by default)
DROP POLICY IF EXISTS "Public Read Access" ON public.system_logs;
DROP POLICY IF EXISTS "Authenticated Insert" ON public.system_logs;

-- Optionally allow Admins to read via Frontend if needed (currently backend handles it)
CREATE POLICY "Admin Read Access" ON public.system_logs
    FOR SELECT TO authenticated
    USING (
        EXISTS (
            SELECT 1 FROM public.profiles
            WHERE id = auth.uid()
            AND role IN ('admin', 'neroferno', 'killu', 'killuwu', 'developer')
        )
    );


-- 2. PROFILES SECURITY
-- Profiles are publicly visible but restricted for updates.
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Public Read Access" ON public.profiles;
DROP POLICY IF EXISTS "Users can update own profile" ON public.profiles;

CREATE POLICY "Public Read Access" ON public.profiles
    FOR SELECT USING (true);

-- Allow users to update their own row, but we use a Trigger to protect specific columns
CREATE POLICY "Users can update own profile" ON public.profiles
    FOR UPDATE TO authenticated
    USING (id = auth.uid())
    WITH CHECK (id = auth.uid());

-- 3. COLUMN PROTECTION TRIGGER
-- Prevent users from changing their 'role', 'money', or 'medals' via the frontend API.
CREATE OR REPLACE FUNCTION public.protect_profile_critical_columns()
RETURNS TRIGGER AS $$
BEGIN
    -- Allow Service Role to do anything
    IF (auth.jwt() ->> 'role') = 'service_role' THEN
        RETURN NEW;
    END IF;

    -- Check for unauthorized changes
    IF NEW.role IS DISTINCT FROM OLD.role THEN
        RAISE EXCEPTION 'You are not authorized to change your role.';
    END IF;

    IF NEW.money IS DISTINCT FROM OLD.money THEN
        RAISE EXCEPTION 'You cannot modify your money directly.';
    END IF;
    
    -- Optionally protect medals if they are managed by system
    -- IF NEW.medals IS DISTINCT FROM OLD.medals THEN
    --     RAISE EXCEPTION 'You cannot modify your medals directly.';
    -- END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

DROP TRIGGER IF EXISTS on_profile_update_protect ON public.profiles;

CREATE TRIGGER on_profile_update_protect
    BEFORE UPDATE ON public.profiles
    FOR EACH ROW
    EXECUTE FUNCTION public.protect_profile_critical_columns();
