-- Create table for profile wall comments
CREATE TABLE IF NOT EXISTS public.profile_comments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    profile_id UUID REFERENCES auth.users(id) ON DELETE CASCADE, -- Owner of the profile
    author_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,  -- Author of the comment
    content TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Indices for performance
CREATE INDEX IF NOT EXISTS idx_profile_comments_profile_id ON public.profile_comments(profile_id);

-- Enable RLS
ALTER TABLE public.profile_comments ENABLE ROW LEVEL SECURITY;

-- 1. Anyone can view comments
CREATE POLICY "Public Read Access" ON public.profile_comments
    FOR SELECT USING (true);

-- 2. Authenticated users can post comments
CREATE POLICY "Authenticated Insert" ON public.profile_comments
    FOR INSERT TO authenticated
    WITH CHECK (auth.uid() = author_id);

-- 3. Only author OR profile owner OR admins can delete
CREATE POLICY "Delete Policy" ON public.profile_comments
    FOR DELETE TO authenticated
    USING (
        auth.uid() = author_id OR 
        auth.uid() = profile_id OR
        EXISTS (
            SELECT 1 FROM public.profiles
            WHERE id = auth.uid()
            AND role IN ('admin', 'neroferno', 'killu', 'killuwu', 'developer')
        )
    );
