-- Create table for Wiki Articles
CREATE TABLE IF NOT EXISTS public.wiki_articles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug TEXT UNIQUE NOT NULL,
    title TEXT NOT NULL,
    content TEXT NOT NULL,
    category TEXT DEFAULT 'general',
    author_id UUID REFERENCES auth.users(id) ON DELETE SET NULL,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Indices
CREATE INDEX IF NOT EXISTS idx_wiki_articles_slug ON public.wiki_articles(slug);
CREATE INDEX IF NOT EXISTS idx_wiki_articles_category ON public.wiki_articles(category);

-- Enable RLS
ALTER TABLE public.wiki_articles ENABLE ROW LEVEL SECURITY;

-- Policies
CREATE POLICY "Public Read Access" ON public.wiki_articles
    FOR SELECT USING (true);

-- Admin/Staff can manage articles
CREATE POLICY "Admin All Access" ON public.wiki_articles
    FOR ALL TO authenticated
    USING (
        EXISTS (
            SELECT 1 FROM public.profiles
            WHERE id = auth.uid()
            AND role IN ('admin', 'neroferno', 'killu', 'killuwu', 'developer')
        )
    );

-- Function to handle updated_at
CREATE OR REPLACE FUNCTION handle_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger for updated_at
CREATE TRIGGER set_wiki_updated_at
BEFORE UPDATE ON public.wiki_articles
FOR EACH ROW
EXECUTE FUNCTION handle_updated_at();
