-- Create table for World Locations and Lore
CREATE TABLE IF NOT EXISTS public.world_locations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    description TEXT NOT NULL,
    long_description TEXT NOT NULL,
    coords VARCHAR(50) DEFAULT '???',
    image_url TEXT,
    is_coming_soon BOOLEAN DEFAULT FALSE,
    authors JSONB DEFAULT '[]'::jsonb, -- Array of objects: { name: string, role: string }
    sort_order INTEGER DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable RLS
ALTER TABLE world_locations ENABLE ROW LEVEL SECURITY;

-- Policies
CREATE POLICY "Public Read Access" ON world_locations
    FOR SELECT USING (true);

CREATE POLICY "Admin All Access" ON world_locations
    FOR ALL TO authenticated
    USING (
        EXISTS (
            SELECT 1 FROM public.profiles 
            WHERE id = auth.uid() 
            AND role IN ('admin', 'neroferno', 'killu', 'killuwu', 'developer')
        )
    );
